"""Initial migration.

Revision ID: 80f5a3c174b3
Revises: 
Create Date: 2024-04-27 17:41:47.586349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f5a3c174b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('title_en', sa.String(length=100), nullable=True),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('title_ru', sa.String(length=100), nullable=True),
    sa.Column('description_ru', sa.String(length=500), nullable=True),
    sa.Column('title_uz', sa.String(length=100), nullable=True),
    sa.Column('description_uz', sa.String(length=500), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('card')
    # ### end Alembic commands ###
