"""empty message

Revision ID: d52e24d24e91
Revises: 1c7faaf6b7dc
Create Date: 2024-04-13 16:40:36.855901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52e24d24e91'
down_revision = '1c7faaf6b7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('title_ru', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_ru', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('title_uz', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_uz', sa.String(length=500), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('description_uz')
        batch_op.drop_column('title_uz')
        batch_op.drop_column('description_ru')
        batch_op.drop_column('title_ru')
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    # ### end Alembic commands ###
